version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: latihan
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: